"""DashSet-backed set primitive."""

from __future__ import annotations

from typing import Generic, TypeVar

_T = TypeVar("_T")


class ConcurrentSet(Generic[_T]):
    def __init__(self) -> None: ...

    def __len__(self) -> int: ...
    def __contains__(self, value: object) -> bool: ...
    def add(self, value: _T) -> None: ...
    def discard(self, value: _T) -> None: ...
    def remove(self, value: _T) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> ConcurrentSet[_T]: ...


__all__ = ["ConcurrentSet"]
